---
# tasks file for sbaerlocher.yaourt
- debug:
    msg: "ansible_distribution {{ ansible_distribution }}  ansible_os_family {{ ansible_os_family }}"

- name: "Install base-devel"
  package:
      name: base-devel
      state: present

- name: "Using all cpu for xz compression"
  lineinfile:
      dest: /etc/makepkg.conf
      state: present
      regexp: "^COMPRESSXZ="
      line: "COMPRESSXZ=(xz -T0 -c -z -)"

- name: "Set make glafs for all cpus"
  lineinfile:
      dest: /etc/makepkg.conf
      state: present
      regexp: '^MAKEFLAGS'
      line: 'MAKEFLAGS="-j"'

- name: "add archlinux.fr repository to pacman"
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
  when: ansible_distribution == "Archlinux"
  tags:
    - packages
 
- name: "Clone packaue-query"
  git:
      repo: https://aur.archlinux.org/package-query.git
      dest: /tmp/package-query
      version: master
  become: yes
  become_user: "{{ aur_user }}"
  when: ansible_distribution == "Archlinux"
  tags:
    - packages

- name: "install packaue-query"
  command:
      cmd: makepkg -si --noconfirm
      chdir: /tmp/package-query
  become: yes
  become_user: "{{ aur_user }}"
  when: ansible_distribution == "Archlinux"
  tags:
    - packages

- name: "Clone yaourt from git"
  git:
      repo: https://aur.archlinux.org/yaourt.git
      dest: /tmp/yaourt
      version: master
  become: yes
  become_user: "{{ aur_user }}"
  when: ansible_distribution == "Archlinux"
  tags:
    - packages

- name: "install yaourt from git"
  command:
      cmd: makepkg -si --noconfirm
      chdir: /tmp/yaourt
  become: yes
  become_user: "{{ aur_user }}"
  when: ansible_distribution == "Archlinux"
  tags:
    - packages
