---
# tasks file for sbaerlocher.yaourt
- debug:
    msg: "ansible_distribution {{ ansible_distribution }}  ansible_os_family {{ ansible_os_family }}"
- name: "add archlinux.fr repository to pacman"
  lineinfile:
    dest: "/etc/pacman.conf"
    state: "present"
    line: "{{ item }}"
  with_items:
    - "[archlinuxfr]"
    - "SigLevel = Never"
    - "Server = http://repo.archlinux.fr/$arch"
  when: ansible_distribution == "Archlinux"
  tags:
    - packages
    
- name: "Clone packaue-query"
  git:
      repo: https://aur.archlinux.org/package-query.git
      dest: /tmp/package-query
      version: master
  when: ansible_distribution == "Archlinux"
  tags:
    - packages

- name: "install packaue-query"
  shell:
      cmd: makepkg -si
      chdir: /tmp/package-query
  when: ansible_distribution == "Archlinux"
  tags:
    - packages

- name: "Clone yaourt from git"
  git:
      repo: git clone https://aur.archlinux.org/yaourt.git
      dest: /tmp/yaourt
      version: master
  when: ansible_distribution == "Archlinux"
  tags:
    - packages

- name: "install yaourt from git"
  shell:
      cmd: makepkg -si
      chdir: /tmp/yaourt
  when: ansible_distribution == "Archlinux"
  tags:
    - packages
